# Generated by Django 3.1.7 on 2021-03-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210304_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='real_cost',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='rental',
            name='real_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='real_stock',
            field=models.IntegerField(default=0),
        ),
    ]
