# Generated by Django 3.1.7 on 2021-03-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20210304_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='real_cost',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='real_stock',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='stock',
        ),
        migrations.DeleteModel(
            name='VehicleStock',
        ),
    ]
